#!/bin/sh

# Copyright (c) 2012 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

shrinkgit() {
        local gitstop="$(du -sk .git|awk '{print $1}')"
	local starts=$SECONDS
	printf "start: %7d gc: " $gitstop
        ( git repack && git gc --aggressive ) > .git/shrink.log 2>&1 || \
		cat .git/shrink.log
        local gitsm="$(du -sk .git|awk '{print $1}')"
	printf "%7d diff: %7d (%ds)\n" $gitsm $(echo "$gitstop - $gitsm"|bc) \
	    $((SECONDS - starts))
}

[ -d .git ] || exit 1
shrinkgit
