#!/bin/sh

shrinkgit() {
        gitstop="$(du -sk .git)"
        git repack && git gc --aggressive
        gitsm="$(du -sk .git)"
        echo "before ${gitstop}"
        echo " after ${gitsm}"
}

[ -d .git ] || exit 1
shrinkgit
